"""Init

Revision ID: aba3ee35929c
Revises: 8810fcec8768
Create Date: 2023-04-24 23:39:36.021177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba3ee35929c'
down_revision = '8810fcec8768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_born_day'), 'contacts', ['born_day'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_second_name'), 'contacts', ['second_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_second_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_born_day'), table_name='contacts')
    # ### end Alembic commands ###
